spring:
    h2:
        console:
            enabled: true  # H2 웹 콘솔을 사용하겠다는 의미
            path: /h2-console  # 콘솔의 경로

    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:tcp://localhost/~/web_miniproject;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
        username: sa
        password: 
            

    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                format_sql: true


    devtools:
        livereload:
            enabled: true # thymeleaf 참조 경로 
            
    thymeleaf:
        prefix: classpath:/templates/ 
        suffix: .html





logging:
    level:
        org.hibernate.SQL: debug